Crafting["Wood Crafting"] = {
    ["Chairs"] = {
        ["Dining Chairs"] = {
            { ["chair70"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair96"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair45"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair46"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair6"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair68"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair67"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair103"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair104"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair102"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair22"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair23"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair44"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair7"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair15"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair9"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair16"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair18"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair19"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair48"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair49"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair37"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair105"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair110"] = { ["wood"] = 1, }, amount = 1 },
        },
        ["House Chairs"] = {
            { ["chair71"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair107"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair84"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair1"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair2"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair3"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair8"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair13"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair14"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair17"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair40"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair50"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair58"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair59"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair61"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair65"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair73"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair74"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair75"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair78"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair80"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair82"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair83"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair85"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair86"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair87"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair88"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair89"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair90"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair91"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair92"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair95"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair101"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair81"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair106"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair108"] = { ["wood"] = 1, }, amount = 1 },
        },
        ["Office Chairs"] = {
            { ["chair25"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair26"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair10"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair11"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair20"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair27"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair28"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair29"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair30"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair31"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair32"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair33"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair34"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair35"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair36"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair60"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair76"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair77"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair79"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair93"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair94"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair98"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair99"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair100"] = { ["wood"] = 1, }, amount = 1 },
        },
        ["Outdoor Chairs"] = {
            { ["chair62"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair63"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair64"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair50"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair97"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair21"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair39"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair66"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair109"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair41"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair42"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair43"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair47"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair51"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair53"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair72"] = { ["wood"] = 1, }, amount = 1 },
        },
        ["Used Chairs"] = {
            { ["chair4"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair5"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair12"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair24"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair38"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair52"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair54"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair55"] = { ["wood"] = 1, }, amount = 1 },
            { ["chair56"] = { ["wood"] = 1, }, amount = 1 },
        },
    },
    ["Other"] = {
        ["Tools"] = {
            { ["walkstick"] = { ["wood"] = 2 }, amount = 1 },
            { ["skateboard"] = { ["wood"] = 3, ["metalscrap"] = 2, ["rubber"] = 2 }, amount = 1 },
            { ["notepad"] = { ["paper"] = 5 }, amount = 1 },
        },
        ["Crafting Materials"] = {
            { ["charcoal"]  = { ["bark"] = 2, }, amount = 1 },
        },
        ["Origami"] = {
            { ["origami1"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami2"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami3"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami4"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami5"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami6"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami7"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami8"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami9"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami10"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami11"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami12"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami13"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami14"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami15"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami16"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami17"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami18"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami19"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami20"] = { ["paper"] = 3 }, amount = 1 },
            { ["origami21"] = { ["paper"] = 3 }, amount = 1 },
        },
    },
    ["Hardware"] = {
        ["Fireworks"] = {
            { ["firework1"] = { ["paper"] = 10, ["pistol_ammo"] = 1, }, amount = 1 },
            { ["firework2"] = { ["paper"] = 10, ["pistol_ammo"] = 1, }, amount = 1 },
            { ["firework3"] = { ["paper"] = 10, ["pistol_ammo"] = 1, }, amount = 1 },
            { ["firework4"] = { ["paper"] = 10, ["pistol_ammo"] = 1, }, amount = 1 },
        },
        ["Cardboard"] = {
            { ["cardhat"] = { ["paper"] = 20, }, amount = 1 },
        },
    },
}

Crafting["Illegal"] = {
    ["Drug Related"] = {
        ["Weed"] = {
            { ["rolling_paper"] = { ["paper"] = 4 }, amount = 4 },
            { ["weed_nutrition"] = { ["bark"] = 4 }, amount = 4 },
        },
    },
    ["Forgery"] = {
        ["Licences"] = {
            { ["fakecert"] = { ["paper"] = 1 }, amount = 1 },
            { ["fakeweaplicence"] = { ["paper"] = 1 }, amount = 1 },
            { ["fakedrivelicence"] = { ["paper"] = 1 }, amount = 1 },
            { ["fakelawyer"] = { ["paper"] = 1 }, amount = 1 },
        },
        ["Cash"] = {
            { ["fakecash"] = { ["paper"] = 1 }, amount = 1 },
            { ["fakecash"] = { ["paper"] = 10 }, amount = 10 },
            { ["fakecash"] = { ["paper"] = 100 }, amount = 100 },
        },
    },
    ["Weapons"] = {
        ["Weapon Parts"] ={
            { ["hammerhandle"] = { ["wood"] = 2 }, amount = 1 },
            { ["batbase"] = { ["wood"] = 4 }, amount = 1 },
            { ["axehandle"] = { ["wood"] = 3 }, amount = 1 },
        },
        ["Weapons"] ={
            { ["weapon_hammer"] = { ["hammerhandle"] = 1, ["steel"] = 2 }, amount = 1 },
            { ["weapon_bat"] = { ["batbase"] = 1, ["rubber"] = 2 }, amount = 1 },
            { ["weapon_stone_hatchet"] = { ["axehandle"] = 1, ["metalscrap"] = 2, }, amount = 1 },
            { ["weapon_poolcue"] = { ["wood"] = 2, }, amount = 1 },
            { ["weapon_musket"] = { ["wood"] = 2, }, amount = 1 },
            { ["weapon_battleaxe"] = { ["axehandle"] = 1, ["steel"] = 2, }, amount = 1 },
        },
    },
}