local SD = exports['sd_lib']:getLib()

if Config.MLOType == 'gabz' then
function firstDoor()
    TriggerServerEvent('sd-bobcat:server:removeItem', Config.Items.Thermite)
    SD.utils.LoadAnim("anim@heists@ornate_bank@thermal_charge")
    SD.utils.LoadModel("hei_p_m_bag_var22_arm_s")
    SD.utils.LoadPtfxAsset("scr_ornate_heist")
    local ped = PlayerPedId()
    
    SetEntityHeading(ped, 88.17)
    Wait(100)
    local rotx, roty, rotz = table.unpack(vec3(GetEntityRotation(PlayerPedId())))
    local bagscene = NetworkCreateSynchronisedScene(914.74, -2121.97, 31.25, rotx, roty, rotz + 1.1, 2, false, false, 1065353216, 0, 1.3)
    local bag = CreateObject(GetHashKey("hei_p_m_bag_var22_arm_s"), 914.74, -2121.97, 31.23,  true,  true, false)
    
    SetEntityCollision(bag, false, true)
    NetworkAddPedToSynchronisedScene(ped, bagscene, "anim@heists@ornate_bank@thermal_charge", "thermal_charge", 1.2, -4.0, 1, 16, 1148846080, 0)
    NetworkAddEntityToSynchronisedScene(bag, bagscene, "anim@heists@ornate_bank@thermal_charge", "bag_thermal_charge", 4.0, -8.0, 1)
    -- SetPedComponentVariation(ped, 5, 0, 0, 0)
    NetworkStartSynchronisedScene(bagscene)
    Wait(1500)
    local x, y, z = table.unpack(GetEntityCoords(ped))
    local bomb = CreateObject(GetHashKey("hei_prop_heist_thermite"), x, y, z + 0.3,  true,  true, true)
    
    SetEntityCollision(bomb, false, true)
    AttachEntityToEntity(bomb, ped, GetPedBoneIndex(ped, 28422), 0, 0, 0, 0, 0, 200.0, true, true, false, true, 1, true)
    Wait(2000)
    DeleteObject(bag)
    -- SetPedComponentVariation(ped, 5, 45, 0, 0)
    DetachEntity(bomb, 1, 1)
    FreezeEntityPosition(bomb, true)
    TriggerServerEvent("sd-bobcat:server:particles", method)
    SetPtfxAssetNextCall("scr_ornate_heist")
    local effect = StartParticleFxLoopedAtCoord("scr_heist_ornate_thermal_burn", ptfx, 0.0, 0.0, 0.0, 1.0, false, false, false, false)
    
    NetworkStopSynchronisedScene(bagscene)
    TaskPlayAnim(ped, "anim@heists@ornate_bank@thermal_charge", "cover_eyes_intro", 8.0, 8.0, 1000, 36, 1, 0, 0, 0)
    TaskPlayAnim(ped, "anim@heists@ornate_bank@thermal_charge", "cover_eyes_loop", 8.0, 8.0, 3000, 49, 1, 0, 0, 0)
    Wait(5000)
    ClearPedTasks(ped)
    DeleteObject(bomb)
    StopParticleFxLooped(effect, 0)
    TriggerEvent("sd-bobcat:client:changeDoorlock", 'bobcatfirst', false) 
end 

function secondDoor() 
    TriggerServerEvent('sd-bobcat:server:removeItem', Config.Items.Thermite)
    SD.utils.LoadAnim("anim@heists@ornate_bank@thermal_charge")
    SD.utils.LoadModel("hei_p_m_bag_var22_arm_s")
    SD.utils.LoadPtfxAsset("scr_ornate_heist")
    local ped = PlayerPedId()

    SetEntityHeading(ped, 85.85)
    Wait(100)
    local rotx, roty, rotz = table.unpack(vec3(GetEntityRotation(PlayerPedId())))
    local bagscene = NetworkCreateSynchronisedScene(908.61, -2120.11, 31.23, rotx, roty, rotz + 1.1, 2, false, false, 1065353216, 0, 1.3)
    local bag = CreateObject(GetHashKey("hei_p_m_bag_var22_arm_s"), 908.61, -2120.11, 31.23,  true,  true, false)

    SetEntityCollision(bag, false, true)
    NetworkAddPedToSynchronisedScene(ped, bagscene, "anim@heists@ornate_bank@thermal_charge", "thermal_charge", 1.2, -4.0, 1, 16, 1148846080, 0)
    NetworkAddEntityToSynchronisedScene(bag, bagscene, "anim@heists@ornate_bank@thermal_charge", "bag_thermal_charge", 4.0, -8.0, 1)
    -- SetPedComponentVariation(ped, 5, 0, 0, 0)
    NetworkStartSynchronisedScene(bagscene)
    Wait(1500)
    local x, y, z = table.unpack(GetEntityCoords(ped))
    local bomb = CreateObject(GetHashKey("hei_prop_heist_thermite"), x, y, z + 0.4,  true,  true, true)

    SetEntityCollision(bomb, false, true)
    AttachEntityToEntity(bomb, ped, GetPedBoneIndex(ped, 28422), 0, 0, 0, 0, 0, 200.0, true, true, false, true, 1, true)
    Wait(2000)
    DeleteObject(bag)
    -- SetPedComponentVariation(ped, 5, 45, 0, 0)
    DetachEntity(bomb, 1, 1)
    FreezeEntityPosition(bomb, true)
    TriggerServerEvent("sd-bobcat:server:particles2", method)
    SetPtfxAssetNextCall("scr_ornate_heist")
    local effect = StartParticleFxLoopedAtCoord("scr_heist_ornate_thermal_burn", ptfx, 0.0, 0.0, 0.0, 1.0, false, false, false, false)

    NetworkStopSynchronisedScene(bagscene)
    TaskPlayAnim(ped, "anim@heists@ornate_bank@thermal_charge", "cover_eyes_intro", 8.0, 8.0, 1000, 36, 1, 0, 0, 0)
    TaskPlayAnim(ped, "anim@heists@ornate_bank@thermal_charge", "cover_eyes_loop", 8.0, 8.0, 3000, 49, 1, 0, 0, 0)
    Wait(5000)
    ClearPedTasks(ped)
    DeleteObject(bomb)
    StopParticleFxLooped(effect, 0)
    TriggerEvent("sd-bobcat:client:changeDoorlock", 'bobcatsecond', false) 
end

function bombplant(timer)
    TriggerServerEvent('sd-bobcat:server:removeItem', Config.Items.Bomb)
    SD.utils.LoadAnim("anim@heists@ornate_bank@thermal_charge")
    SD.utils.LoadModel("hei_p_m_bag_var22_arm_s")
    SD.utils.LoadPtfxAsset("scr_ornate_heist")
    local ped = PlayerPedId()

    SetEntityHeading(ped, 354.05)
    Citizen.Wait(100)
    local rotx, roty, rotz = table.unpack(vec3(GetEntityRotation(PlayerPedId())))
    local bagscene = NetworkCreateSynchronisedScene(887.43, -2130.06, 31.23, rotx, roty, rotz + 1.1, 2, false, false, 1065353216, 0, 1.3)
    local bag = CreateObject(GetHashKey("hei_p_m_bag_var22_arm_s"), 887.43, -2130.06, 31.23,  true,  true, false)

    SetEntityCollision(bag, false, true)
    NetworkAddPedToSynchronisedScene(ped, bagscene, "anim@heists@ornate_bank@thermal_charge", "thermal_charge", 1.2, -4.0, 1, 16, 1148846080, 0)
    NetworkAddEntityToSynchronisedScene(bag, bagscene, "anim@heists@ornate_bank@thermal_charge", "bag_thermal_charge", 4.0, -8.0, 1)
    -- SetPedComponentVariation(ped, 5, 0, 0, 0)
    NetworkStartSynchronisedScene(bagscene)
    Citizen.Wait(1500)
    local x, y, z = table.unpack(GetEntityCoords(ped))
    local bomba = CreateObject(GetHashKey("ch_prop_ch_explosive_01a"), x, y, z + 160,  true,  true, true)

    SetEntityCollision(bomba, false, true)
    AttachEntityToEntity(bomba, ped, GetPedBoneIndex(ped, 28422), 0, 0, 0, 0, 0, 200.0, true, true, false, true, 1, true)
    Citizen.Wait(2000)
    DeleteObject(bag)
    -- SetPedComponentVariation(ped, 5, 45, 0, 0)
    DetachEntity(bomba, 1, 1)
    FreezeEntityPosition(bomba, true)
    SetPtfxAssetNextCall("scr_ornate_heist")
    local effect = StartParticleFxLoopedAtCoord("scr_heist_ornate_thermal_burn", ptfx, 0.0, 0.0, 0.0, 1.0, false, false, false, false)

    NetworkStopSynchronisedScene(bagscene)
    SD.ShowNotification(Lang:t('success.planted_bomb'), 'success')
    Citizen.Wait(timer)
    ClearPedTasks(ped)
    StopParticleFxLooped(effect, 0)
    TriggerEvent("sd-bobcat:client:explosion")
    DeleteObject(bomba)
end
elseif Config.MLOType == 'nopixel' then
    function firstDoor()
        TriggerServerEvent('sd-bobcat:server:removeItem', Config.Items.Thermite)
        SD.utils.LoadAnim("anim@heists@ornate_bank@thermal_charge")
        SD.utils.LoadModel("hei_p_m_bag_var22_arm_s")
        SD.utils.LoadPtfxAsset("scr_ornate_heist")
        local ped = PlayerPedId()
    
        SetEntityHeading(ped, 170.52)
        Wait(100)
        local rotx, roty, rotz = table.unpack(vec3(GetEntityRotation(PlayerPedId())))
        local bagscene = NetworkCreateSynchronisedScene(882.1660, -2258.35, 30.60, rotx, roty, rotz + 1.1, 2, false, false, 1065353216, 0, 1.3)
        local bag = CreateObject(GetHashKey("hei_p_m_bag_var22_arm_s"), 882.1660, -2258.35, 30.60,  true,  true, false)
    
        SetEntityCollision(bag, false, true)
        NetworkAddPedToSynchronisedScene(ped, bagscene, "anim@heists@ornate_bank@thermal_charge", "thermal_charge", 1.2, -4.0, 1, 16, 1148846080, 0)
        NetworkAddEntityToSynchronisedScene(bag, bagscene, "anim@heists@ornate_bank@thermal_charge", "bag_thermal_charge", 4.0, -8.0, 1)
        -- SetPedComponentVariation(ped, 5, 0, 0, 0)
        NetworkStartSynchronisedScene(bagscene)
        Wait(1500)
        local x, y, z = table.unpack(GetEntityCoords(ped))
        local bomb = CreateObject(GetHashKey("hei_prop_heist_thermite"), x, y, z + 0.3,  true,  true, true)
    
        SetEntityCollision(bomb, false, true)
        AttachEntityToEntity(bomb, ped, GetPedBoneIndex(ped, 28422), 0, 0, 0, 0, 0, 200.0, true, true, false, true, 1, true)
        Wait(2000)
        DeleteObject(bag)
        -- SetPedComponentVariation(ped, 5, 45, 0, 0)
        DetachEntity(bomb, 1, 1)
        FreezeEntityPosition(bomb, true)
        TriggerServerEvent("sd-bobcat:server:particles", method)
        SetPtfxAssetNextCall("scr_ornate_heist")
        local effect = StartParticleFxLoopedAtCoord("scr_heist_ornate_thermal_burn", ptfx, 0.0, 0.0, 0.0, 1.0, false, false, false, false)
    
        NetworkStopSynchronisedScene(bagscene)
        TaskPlayAnim(ped, "anim@heists@ornate_bank@thermal_charge", "cover_eyes_intro", 8.0, 8.0, 1000, 36, 1, 0, 0, 0)
        TaskPlayAnim(ped, "anim@heists@ornate_bank@thermal_charge", "cover_eyes_loop", 8.0, 8.0, 3000, 49, 1, 0, 0, 0)
        Wait(5000)
        ClearPedTasks(ped)
        DeleteObject(bomb)
        StopParticleFxLooped(effect, 0)
        TriggerEvent("sd-bobcat:client:changeDoorlock", 'bobcatfirst', false) 
    end
    
    function secondDoor() 
        TriggerServerEvent('sd-bobcat:server:removeItem', Config.Items.Thermite)
        SD.utils.LoadAnim("anim@heists@ornate_bank@thermal_charge")
        SD.utils.LoadModel("hei_p_m_bag_var22_arm_s")
        SD.utils.LoadPtfxAsset("scr_ornate_heist")
        local ped = PlayerPedId()
    
        SetEntityHeading(ped, 170.52)
        Wait(100)
        local rotx, roty, rotz = table.unpack(vec3(GetEntityRotation(PlayerPedId())))
        local bagscene = NetworkCreateSynchronisedScene(880.5080, -2264.50, 30.571, rotx, roty, rotz + 1.1, 2, false, false, 1065353216, 0, 1.3)
        local bag = CreateObject(GetHashKey("hei_p_m_bag_var22_arm_s"), 880.5080, -2264.50, 30.571,  true,  true, false)
    
        SetEntityCollision(bag, false, true)
        NetworkAddPedToSynchronisedScene(ped, bagscene, "anim@heists@ornate_bank@thermal_charge", "thermal_charge", 1.2, -4.0, 1, 16, 1148846080, 0)
        NetworkAddEntityToSynchronisedScene(bag, bagscene, "anim@heists@ornate_bank@thermal_charge", "bag_thermal_charge", 4.0, -8.0, 1)
        -- SetPedComponentVariation(ped, 5, 0, 0, 0)
        NetworkStartSynchronisedScene(bagscene)
        Wait(1500)
        local x, y, z = table.unpack(GetEntityCoords(ped))
        local bomb = CreateObject(GetHashKey("hei_prop_heist_thermite"), x, y, z + 0.4,  true,  true, true)
    
        SetEntityCollision(bomb, false, true)
        AttachEntityToEntity(bomb, ped, GetPedBoneIndex(ped, 28422), 0, 0, 0, 0, 0, 200.0, true, true, false, true, 1, true)
        Wait(2000)
        DeleteObject(bag)
        -- SetPedComponentVariation(ped, 5, 45, 0, 0)
        DetachEntity(bomb, 1, 1)
        FreezeEntityPosition(bomb, true)
        TriggerServerEvent("sd-bobcat:server:particles2", method)
        SetPtfxAssetNextCall("scr_ornate_heist")
        local effect = StartParticleFxLoopedAtCoord("scr_heist_ornate_thermal_burn", ptfx, 0.0, 0.0, 0.0, 1.0, false, false, false, false)
    
        NetworkStopSynchronisedScene(bagscene)
        TaskPlayAnim(ped, "anim@heists@ornate_bank@thermal_charge", "cover_eyes_intro", 8.0, 8.0, 1000, 36, 1, 0, 0, 0)
        TaskPlayAnim(ped, "anim@heists@ornate_bank@thermal_charge", "cover_eyes_loop", 8.0, 8.0, 3000, 49, 1, 0, 0, 0)
        Wait(5000)
        ClearPedTasks(ped)
        DeleteObject(bomb)
        StopParticleFxLooped(effect, 0)
        TriggerEvent("sd-bobcat:client:changeDoorlock", 'bobcatsecond', false) 
    end
    
    function bombplant(timer)
        TriggerServerEvent('sd-bobcat:server:removeItem', Config.Items.Bomb)
        SD.utils.LoadAnim("anim@heists@ornate_bank@thermal_charge")
        SD.utils.LoadModel("hei_p_m_bag_var22_arm_s")
        SD.utils.LoadPtfxAsset("scr_ornate_heist")
        local ped = PlayerPedId()
    
        SetEntityHeading(ped, 79.95)
        Citizen.Wait(100)
        local rotx, roty, rotz = table.unpack(vec3(GetEntityRotation(PlayerPedId())))
        local bagscene = NetworkCreateSynchronisedScene(890.35430908203,-2285.6541015625,30.541303253174, rotx, roty, rotz + 1.1, 2, false, false, 1065353216, 0, 1.3)
        local bag = CreateObject(GetHashKey("hei_p_m_bag_var22_arm_s"), 890.35430908203,-2285.6541015625,30.541303253174,  true,  true, false)
    
        SetEntityCollision(bag, false, true)
        NetworkAddPedToSynchronisedScene(ped, bagscene, "anim@heists@ornate_bank@thermal_charge", "thermal_charge", 1.2, -4.0, 1, 16, 1148846080, 0)
        NetworkAddEntityToSynchronisedScene(bag, bagscene, "anim@heists@ornate_bank@thermal_charge", "bag_thermal_charge", 4.0, -8.0, 1)
        -- SetPedComponentVariation(ped, 5, 0, 0, 0)
        NetworkStartSynchronisedScene(bagscene)
        Citizen.Wait(1500)
        local x, y, z = table.unpack(GetEntityCoords(ped))
        local bomba = CreateObject(GetHashKey("ch_prop_ch_explosive_01a"), x, y, z + 160,  true,  true, true)
    
        SetEntityCollision(bomba, false, true)
        AttachEntityToEntity(bomba, ped, GetPedBoneIndex(ped, 28422), 0, 0, 0, 0, 0, 200.0, true, true, false, true, 1, true)
        Citizen.Wait(2000)
        DeleteObject(bag)
        -- SetPedComponentVariation(ped, 5, 45, 0, 0)
        DetachEntity(bomba, 1, 1)
        FreezeEntityPosition(bomba, true)
        SetPtfxAssetNextCall("scr_ornate_heist")
    
        NetworkStopSynchronisedScene(bagscene)
        SD.ShowNotification(Lang:t('success.planted_bomb'), 'success')
        Citizen.Wait(timer)
        TriggerEvent("sd-bobcat:client:explosion")
        DeleteObject(bomba)
    end
end