CREATE TABLE IF NOT EXISTS `druglabs` (
  `id` INT NULL AUTO_INCREMENT,
  `coords` JSON NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `owner` VARCHAR(45) NULL,
  `code` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL DEFAULT 0,
  `price` INT NOT NULL,
  `owned` INT NOT NULL,
  PRIMARY KEY (`id`)
)
AUTO_INCREMENT = 1;